[versions]
agp = "8.9.0"
kotlin = "2.1.21"
compose-plugin = "1.8.0"
android-compileSdk = "35"
android-minSdk = "24"
android-targetSdk = "35"

[libraries]
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version = "1.10.1" }

[plugins]
multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
jetbrainsCompose = { id = "org.jetbrains.compose", version.ref = "compose-plugin" }
android-application = { id = "com.android.application", version.ref = "agp" }
